name = "kings-league"
main = "api/index.js"
compatibility_date = "2023-01-05"

[site]
bucket = "./assets"

[env.production]
vars = { ENVIRONMENT = "production" }
routes = [
	{ pattern: "api.kingsleague.dev", custom_domain = true }
]