name: Scrape Kings League website

# Cuando quiero que esto suceda.
on:
  workflow_dispatch: # para correr la GA desde github
  repository_dispatch: # para utilizar un webhook, curl
    types:
      - webhook
  schedule: # progamamos para que ocurra cada cierto tiempo
    - cron: 0 */1 * * 0 # se ejecutara cada hora de los dias domingos

# el trabajo que queremos que haga
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: | # this is the syntax to run more than one command
          yarn install
          node scraping/leaderboard.js
          git config user.name kings-league-bot
          git add -A
          git commit -m "[bot] Update Kings League Database"
          git push origin main
